[advisories]
# The path where the advisory database is cloned/fetched into
db-path = "~/.cargo/advisory-db"

# The url(s) of the advisory databases to clone and fetch
db-urls = ["https://github.com/RustSec/advisory-db.git"]

# The lint level for crates that have been yanked from their source registry
yanked = "warn"

[ignore]
# Ignore the unmaintained paste crate warning
id = "RUSTSEC-2024-0436"

[information]
# Disable vulnerability database fetching
# disable-fetch = true

# Disable output of vulnerabilities that have been patched
# no-patch = true
